### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by ThrashJazzAssassin** [stufisher/LiveOSC2#5]
I've been trying LiveOSC2 on Live9.7.2 and it doesn't respond to any OSC messages. I know it's receiving them because I checked with OSCmonitor from https://github.com/Ableton/m4l-connection-kit

Are there installation instructions missing in the docs? or has it been broken by 2 years of Ableton Live updates?

Thanks

**Comment by AdrianoEcker** [comment]
Olá, eu também estou tentando. Se conseguir algo eu te aviso. ok

**Comment by grmcom** [comment]
Hi guys i tried pchdevs fork this week and it seemed to work fine.
https://github.com/pchdev/LiveOSC2

**Comment by AdrianoEcker** [comment]
Which port do you use to send and receive OSC data?
I installed everything correctly but I can not send or receive anything.


![capturar](https://cloud.githubusercontent.com/assets/3848073/26029470/cb7ac872-3803-11e7-81a0-3e36d2ad656e.JPG)

**Comment by stufisher** [comment]
Done a fair few tests today and it seems to work ok for (also fixed a load of bugs, but not ones that stop it running)

**Comment by stufisher** [comment]
@AdrianoEcker send to 9001, recv on 9000

attached is a simple max patch
[osc_tester.maxpat.zip](https://github.com/stufisher/LiveOSC2/files/1002349/osc_tester.maxpat.zip)

**Comment by AdrianoEcker** [comment]
Sim, eu estou usando estas portas mas não consigo resposta.
Eu fiz um teste usando o YecoOSC e funcionou. segue uma imagem do teste.
Mais o YecoOSC não recebe dados somente envia.
E quero enviar e receber.
![image](https://cloud.githubusercontent.com/assets/3848073/26107389/20c7c31a-3a17-11e7-8415-f764302e413c.png)

**Comment by stufisher** [comment]
Please could you test with the attached max patch?

**Comment by ThrashJazzAssassin** [comment]
No such object..?

![osc](https://cloud.githubusercontent.com/assets/15689085/26149662/fba082f2-3af2-11e7-8b58-10898bd24f98.PNG)

**Comment by stufisher** [comment]
Sorry you need the cnamt externals:
http://cnmat.berkeley.edu/downloads

Also, do grab the latest commits, they do fix some broken stuff

**Comment by ThrashJazzAssassin** [comment]
Thanks. I installed cnmat with Max package manager.
Still nothing :-/

![recov](https://cloud.githubusercontent.com/assets/15689085/26150466/59171bdc-3af6-11e7-995a-781fc676b554.gif)

**Comment by stufisher** [comment]
Have you grabbed my latest updates?

Also, i dont know if you tried this, but you cannot run OSC monitor at the same time as LiveOSC, they will fight for the same port. If OSC Monitor is responding LiveOSC cannot have bound to the port.

**Comment by stufisher** [comment]
@AdrianoEcker you have the wrong port, OSCIn should be on 9000 in TouchDesigner

**Comment by ThrashJazzAssassin** [comment]
Yep. All fully updated. 

Live does not respond before I open OSC Monitor.

**Comment by stufisher** [comment]
@ThrashJazzAssassin please start Live, then close it, then attach 
 \Users\[username]\AppData\Roaming\Ableton\Live x.x.x\Preferences\Log.txt

**Comment by ThrashJazzAssassin** [comment]
`2720 ms. RemoteScriptError: import LiveOSC2-master`
[Log.txt](https://github.com/stufisher/LiveOSC2/files/1010707/Log.txt)

**Comment by stufisher** [comment]
Rename LiveOSC2-master to LiveOSC

**Comment by ThrashJazzAssassin** [comment]
That's it! Thank you so much @stufisher

**Comment by AdrianoEcker** [comment]
ok, funcionou aqui também.
Obrigado a todos.
