### ISSUE TITLE
Jump to specific cuepoint

### ISSUE THREAD

**Issue by burkholderm** [stufisher/LiveOSC2#9]
I would like to be able to jump to a specific cuepoint in the arrangement view and get the name of that cuepoint, but don't know how to achieve it. In the LiveAPI documentation I found "Live.Song.CuePoint.jump()" and "Live.Song.CuePoint.name", which looks like what I want to do. Can you add those commands or how can I add them?

http://julienbayle.net/PythonLiveAPI_documentation/Live9.6.xml

Thanks!

**Comment by ccerrillos** [comment]
Added in #10 :D

**Comment by burkholderm** [comment]
Thanks for adding this! I have tested it and it works.
